### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by makiron918** [takumitorii/freemarket_sample_70f#102]
■ URL
IPアドレス：http://18.180.99.238/
Github（最終課題のリポジトリ）：https://github.com/takumitorii/freemarket_sample_70f

■ Basic認証
ID：admin
Pass：2222

■ テスト用アカウント
◯ 購入者用
メールアドレス：gonza@gmail.com
パスワード：22222222

◯ 購入用カード情報
番号：4242424242424242
期限：2022/09
セキュリティカード：123

◯ 出品者用
メールアドレス：doda@gmail.com
パスワード：11111111

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**出品内容を適切にしましょう（公序良俗・著作権に反する画像を使用したり、不適切な文言を使用していない）**
※著作権フリーの画像を使いましょう
<img width="1147" alt="FreemarketSample70f" src="https://user-images.githubusercontent.com/52514431/77503980-6666ec80-6ea2-11ea-8436-39f1b01cda47.png">
**画像がない状態で出品するとエラー画面になります**
※エラーハンドリングしましょう
<img width="1191" alt="Action_Controller__Exception_caught" src="https://user-images.githubusercontent.com/52514431/77504396-8d71ee00-6ea3-11ea-9af4-ad59067831ce.png">

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by makiron918** [comment]
指摘された点を修正しましたので、ご確認お願いいたします。

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
